Format and switch MacOS back to ports
Signed-off-by: Daniel Hansen <dchansen06@gmail.com>

diff --git a/.github/workflows/UnitTestsHOOTL.yml b/.github/workflows/UnitTestsHOOTL.yml
--- a/.github/workflows/UnitTestsHOOTL.yml
+++ b/.github/workflows/UnitTestsHOOTL.yml
@@ -3,13 +3,13 @@ run-name: Unit Tests - ${{ github.ref_name }}
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    types: [ opened, synchronize, reopened, ready_for_review ]
+    types: [opened, synchronize, reopened, ready_for_review]
   workflow_dispatch:
 
 env:
-  ARM_GCC_VERSION: '12.2.Rel1'
+  ARM_GCC_VERSION: "12.2.Rel1"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -25,14 +25,14 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        prefix: [ "Debug", "Release", "MinSizeRel", "RelWithDebInfo" ]
+        prefix: ["Debug", "Release", "MinSizeRel", "RelWithDebInfo"]
         operatingSystem: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
     env:
       SCCACHE_DIR: ${{ github.workspace }}/sccache
       SCCACHE_LOG: "info"
       SCCACHE_ERROR_LOG: ${{ github.workspace }}/sccache-error.log
-      SCCACHE_SERVER_UDS: ${{ matrix.operatingSystem != 'windows-latest' && format('/tmp/sccache-{0}.sock', matrix.prefix) || '' }}
-      SCCACHE_SERVER_PORT: ${{ matrix.operatingSystem == 'windows-latest' && (matrix.prefix == 'Debug' && '4226' || (matrix.prefix == 'Release' && '4227' || (matrix.prefix == 'MinSizeRel' && '4228' || '4229'))) || '' }}
+      SCCACHE_SERVER_UDS: ${{ matrix.operatingSystem == 'ubuntu-latest' && format('/tmp/sccache-{0}.sock', matrix.prefix) || '' }}
+      SCCACHE_SERVER_PORT: ${{ matrix.operatingSystem == 'windows-latest' && (matrix.prefix == 'Debug' && '4226' || (matrix.prefix == 'Release' && '4227' || (matrix.prefix == 'MinSizeRel' && '4228' || '4229'))) || (matrix.operatingSystem == 'macos-latest' && (matrix.prefix == 'Debug' && '4326' || (matrix.prefix == 'Release' && '4327' || (matrix.prefix == 'MinSizeRel' && '4328' || '4329'))) || '') }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -40,12 +40,12 @@ jobs:
           fetch-depth: 1
 
       - name: Install Arm Toolchain
-        uses: carlosperate/arm-none-eabi-gcc-action@0725d97b026acf7fc8e22dfd5bee912998879ba8  # v1.12.3
+        uses: carlosperate/arm-none-eabi-gcc-action@0725d97b026acf7fc8e22dfd5bee912998879ba8 # v1.12.3
         with:
           release: ${{ env.ARM_GCC_VERSION }}
 
       - name: Setup Shared Compilation Cache
-        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
+        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
         with:
           path: ${{ env.SCCACHE_DIR }}
           key: sccache-${{ runner.os }}-${{ env.ARM_GCC_VERSION }}-${{ github.job }}-${{ matrix.prefix }}-${{ github.ref_name }}
@@ -167,7 +167,7 @@ jobs:
 
       - name: Upload Ubuntu RelWithDebInfo Builds
         if: matrix.prefix == 'RelWithDebInfo' && matrix.operatingSystem == 'ubuntu-latest'
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
         with:
           name: firmware-release-with-debug-info
           path: build/${{ matrix.prefix }}/*.elf
@@ -181,23 +181,23 @@ jobs:
     needs: cmake
     runs-on: ${{ matrix.operatingSystem }}
     permissions:
-        contents: read
-        actions: write
+      contents: read
+      actions: write
     strategy:
-        fail-fast: true
-        matrix:
-          operatingSystem: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
+      fail-fast: true
+      matrix:
+        operatingSystem: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft && fromJson('["ubuntu-latest"]') || fromJson('["ubuntu-latest", "windows-latest", "macos-latest"]') }}
     env:
-        SCCACHE_DIR: ${{ github.workspace }}/sccache
-        SCCACHE_LOG: "info"
-        SCCACHE_ERROR_LOG: ${{ github.workspace }}/sccache-error.log
-        SCCACHE_SERVER_UDS: ${{ matrix.operatingSystem != 'windows-latest' && format('/tmp/sccache-{0}.sock', github.job) || '' }}
-        SCCACHE_SERVER_PORT: ${{ matrix.operatingSystem == 'windows-latest' && '4226' || '' }}
+      SCCACHE_DIR: ${{ github.workspace }}/sccache
+      SCCACHE_LOG: "info"
+      SCCACHE_ERROR_LOG: ${{ github.workspace }}/sccache-error.log
+      SCCACHE_SERVER_UDS: ${{ matrix.operatingSystem == 'ubuntu-latest' && format('/tmp/sccache-{0}.sock', github.job) || '' }}
+      SCCACHE_SERVER_PORT: ${{ matrix.operatingSystem == 'windows-latest' && '4226' || (matrix.operatingSystem == 'macos-latest' && '4326' || '') }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
-            fetch-depth: 1
+          fetch-depth: 1
 
       - name: Setup Cache
         uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
@@ -218,105 +218,105 @@ jobs:
         if: matrix.operatingSystem != 'windows-latest'
         shell: bash
         run: |
-            set -o pipefail
-            echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            cmake --preset HOOTLTest -DCMAKE_C_COMPILER_LAUNCHER=sccache 2>&1 | tee -a $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          set -o pipefail
+          echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          cmake --preset HOOTLTest -DCMAKE_C_COMPILER_LAUNCHER=sccache 2>&1 | tee -a $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
 
       - name: CMake Configuration (Windows)
         if: matrix.operatingSystem == 'windows-latest'
         shell: pwsh
         run: |
-            echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            cmake --preset HOOTLTest -DCMAKE_C_COMPILER_LAUNCHER=sccache 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "<details><summary>CMake Configuration (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          cmake --preset HOOTLTest -DCMAKE_C_COMPILER_LAUNCHER=sccache 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
 
       - name: CMake Build (Unix)
         if: matrix.operatingSystem != 'windows-latest'
         shell: bash
         run: |
-            set -o pipefail
-            echo "<details><summary>CMake Build (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            cmake --build --preset HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          set -o pipefail
+          echo "<details><summary>CMake Build (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          cmake --build --preset HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
 
       - name: CMake Build (Windows)
         if: matrix.operatingSystem == 'windows-latest'
         shell: pwsh
         run: |
-            echo "<details><summary>CMake Build (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            cmake --build --preset HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "<details><summary>CMake Build (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          cmake --build --preset HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
 
       - name: Run CTest (Unix)
         if: matrix.operatingSystem != 'windows-latest'
         shell: bash
         run: |
-            set -o pipefail
-            echo "<details open><summary>Run CTest (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
-            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-            echo "" >> $GITHUB_STEP_SUMMARY
-            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          set -o pipefail
+          echo "<details open><summary>Run CTest (HOOTLTest)</summary>" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | tee -a $GITHUB_STEP_SUMMARY
+          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
 
       - name: Run CTest (Windows)
         if: matrix.operatingSystem == 'windows-latest'
         shell: pwsh
         run: |
-            echo "<details open><summary>Run CTest (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "<details open><summary>Run CTest (HOOTLTest)</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          ctest --output-on-failure --test-dir build/HOOTLTest 2>&1 | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
 
       - name: Shared Compilation Cache Errors (Unix)
         if: matrix.operatingSystem != 'windows-latest'
         shell: bash
         run: |
-            set -o pipefail
-            if [ -f "$SCCACHE_ERROR_LOG" ]; then
-              echo "<details><summary>Shared Compilation Cache Errors</summary>" >> $GITHUB_STEP_SUMMARY
-              echo "" >> $GITHUB_STEP_SUMMARY
-              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-              cat "$SCCACHE_ERROR_LOG" | tee -a $GITHUB_STEP_SUMMARY
-              echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
-              echo "" >> $GITHUB_STEP_SUMMARY
-              echo "</details>" >> $GITHUB_STEP_SUMMARY
-            fi
+          set -o pipefail
+          if [ -f "$SCCACHE_ERROR_LOG" ]; then
+            echo "<details><summary>Shared Compilation Cache Errors</summary>" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            cat "$SCCACHE_ERROR_LOG" | tee -a $GITHUB_STEP_SUMMARY
+            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          fi
 
       - name: Shared Compilation Cache Errors (Windows)
         if: matrix.operatingSystem == 'windows-latest'
         shell: pwsh
         run: |
-            if (Test-Path $env:SCCACHE_ERROR_LOG) {
-              echo "<details><summary>Shared Compilation Cache Errors</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              Get-Content $env:SCCACHE_ERROR_LOG | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-              echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
-            }
+          if (Test-Path $env:SCCACHE_ERROR_LOG) {
+            echo "<details><summary>Shared Compilation Cache Errors</summary>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            Get-Content $env:SCCACHE_ERROR_LOG | Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            echo "``````" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            echo "" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+            echo "</details>" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
+          }
 
   valgrind:
     name: Valgrind
@@ -331,7 +331,7 @@ jobs:
           fetch-depth: 1
 
       - name: Set up Valgrind
-        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05  # v1.6.0
+        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
         with:
           packages: valgrind
 
@@ -350,7 +350,7 @@ jobs:
     if: false # TODO Implement formal testing for CANfigurator
     name: Prove CANfigurator
     runs-on: ubuntu-slim
-    permissions: { }
+    permissions: {}
     steps:
       - name: Placeholder for CANfigurator Unit Tests
         run: echo "Placeholder for CANfigurator unit tests using Prove (or some other testing framework)."
@@ -358,9 +358,9 @@ jobs:
   all:
     if: ${{ !github.event.pull_request.draft && always() }}
     name: Completed All HOOTL Unit Tests
-    needs: [ cmake, ctest, valgrind ] # TODO Add prove once implemented
+    needs: [cmake, ctest, valgrind] # TODO Add prove once implemented
     runs-on: ubuntu-slim
-    permissions: { }
+    permissions: {}
     steps:
       - name: Fail HOOTL Unit Tests
         if: > # TODO Add prove once implemented
